
import Filter from "@/components/AllPaths/filter"
import { useEffect, useState } from "react"
import axios from "axios"
import Course from "@/components/Cards/Course"
import { TypeId } from "public/assets/utils/utils"
import { useRouter } from "next/router"
import Head from "next/head"
import { getFilterCourses } from "public/assets/utils/utils"
import LoadingLayout from "@/layouts/LoadingLayout"
import { useDispatch } from "react-redux"
import { SET_LOADING } from "@/redux/reducers/loading"
const AllPathes = () =>{
    const [items,setItems] = useState([])
    const [realData,setRealData] = useState([])
    const router = useRouter()
    const dispatch = useDispatch()
    const {query} = router


    useEffect(()=>{
        dispatch(SET_LOADING(true))
        axios.get("https://test2.plan-b-eg.com/api/Courses/GetAllCourses").then((res)=>{
            if(res.data.length > 0){
                const filteredCourses =  getFilterCourses(res.data,TypeId[query.title])
                setRealData(filteredCourses)
                const customArr =[...filteredCourses]
                customArr.length = 12
                setItems(customArr) 
                dispatch(SET_LOADING(false))      
            }     
        })
    },[])
   
    const recieveFilteredItems = (data) =>{
        setRealData(data)
        const customArr = [...data]
        if(data.length > 12){
            customArr.length = 12
        }     
        setItems(customArr)
        dispatch(SET_LOADING(false))
    }
    const handleMore = () =>{
        const copyData = [...realData]
        copyData.length = items.length + 12
        setItems(copyData)
    }

    return(
        <>
            <Head>
                <title>All Courses</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <LoadingLayout>
                <div className="mr-[8.125vw] ml-[8.7vw]">                 
                    <div className="flex justify-between mt-[28px]">
                        <p className="font-[ar-meduim] 2xl:text-[20px]">النتيجة:{items.length} من {realData.length}</p>
                        <p className="max-lg:text-[14.74px] 2xl:text-[22px] font-[ar-bold] ">التصفيات النشطة</p>  
                    </div>
                    <Filter passFilterdItems={recieveFilteredItems} typeId={TypeId[query.title]}/>          
                    <div className="flex flex-wrap justify-between max-[774px]:justify-center">
                        {items?.map((item)=>(
                            <div className="mb-16 lg:min-h-[376.7px] 2xl:w-[25vw] 2xl:h-[485.6px]  5xl:h-[607px]  max-lg:w-[400px] max-lg:min-h-[387px] md:w-[322px]">
                                <Course data={item}/>
                            </div>            
                        ))}
                    </div>            
                    <button disabled={items.length === realData.length ? true :false}  onClick={handleMore}>حمل المزيد</button>              
                </div> 
            </LoadingLayout>  
        </>        
    )
}

export default AllPathes