import Head from 'next/head'
import NewCourses
 from '@/components/Home/NewCourses'
import OnlineCourses from '@/components/Home/OnlineCourses'
import EducationalTracks from '@/components/Home/EducationalTracks'
import Trainers from '@/components/Home/Trainers'
import Category from '@/components/Home/Category'
import StaticSlider from '@/components/Home/StaticSlider'
import { filterCourses } from '@/assets/utils/functions'
import News from '@/components/Home/News'
import Typo from '@/components/Home/Typo'
import SecondTypo from '@/components/Home/SecondTypo'
import Features from '@/components/Home/Features'
import Subscribe from '@/components/Home/Subscribe'
export default function Home({courses,categoryData,instractors,news}) {
  console.log(courses)
  
 return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <News news={news}/>
      <Features/>  
      <Typo/> 
      <Category data={categoryData}/>
      <NewCourses data={courses.onlineCourses}/>
      <OnlineCourses data={courses.offlineCourses}/>
      <SecondTypo/>
      <EducationalTracks data={courses.paths}/>
      <StaticSlider />
      <Trainers data={instractors}/> 
      <Subscribe/>  
    </>
  )
}
export async function getStaticProps() {
  const res = await fetch(`${process.env.NEXT_PUBLIC_ALL_COURSES}?showInHomePage=true&lang=en`)
  const data = await res.json()

  const courses = filterCourses(data)


  const categoryRes = await fetch(`${process.env.NEXT_PUBLIC_CATEGORIES}?lang=en`)
  const categoryData = await categoryRes.json()

  const instractorsRes = await fetch(`${process.env.NEXT_PUBLIC_ALL_INSTRUCTORS}?lang=en&limit=10&page=1`)
  const instractors = await instractorsRes.json()

  const newsRes = await fetch(`${process.env.NEXT_PUBLIC_ALL_NEWS}?lang=en`)
  const news = await newsRes.json()


  return { props: { courses,categoryData,instractors,news } }
}



